speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_frame: False

decoder_config:
  vocabulary: ../../sp.model

model_config:
  encoder_subsampling:
    type: conv2d
    filters: 256
    kernel_size: 3
    strides: 2
  encoder_dmodel: 256
  encoder_num_blocks: 16
  encoder_head_size: 64
  encoder_num_heads: 4
  encoder_mha_type: relmha
  encoder_kernel_size: 31
  encoder_fc_factor: 1.
  encoder_dropout: 0.1

  encoder_time_reduce_idx: 
    - 7
  encoder_time_recover_idx: 
    - 15

  encoder_conv_use_glu: false
  encoder_ds_subsample: true
  encoder_no_post_ln: true
  encoder_adaptive_scale: true
  encoder_fixed_arch:
    - M
    - s
    - C
    - s

learning_config:
  train_dataset_config:
    augmentation_config:
      time_masking:
        num_masks: 5
        p_upperbound: 0.05
      freq_masking:
        num_masks: 2
        mask_factor: 27
    data_paths: null
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train

  eval_dataset_config:
    data_paths: null
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval

  test_dataset_config:
    data_paths: null
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: False
    stage: test

  optimizer_config:
    beta_1: 0.9
    beta_2: 0.98
    epsilon: 1e-9

  running_config:
    num_epochs: 1000
    filepath: null
    checkpoint:
      filepath: null
      save_best_only: False
      save_weights_only: True
      save_freq: epoch
    states_dir: null
